### ISSUE TITLE
Clang build issue when using c_forpair due to anomymous struct

### ISSUE THREAD

**Issue by ammarhakim** [tylov/STC#18]
It seems that the use of an anonymous struct in the `c_forpair` macro is not supported in clang. The generated code from this macro contains an anonymous struct similar to:
```
  for ( struct { int i, j; } _ = { 25, 35 }; ; )
    ;
```
This will compile on GCC (as does c_forloop). However, clang gives an error: "error: declaration of non-local variable in 'for' loop".

This could be a clang issue, though.

**Comment by tylov** [comment]
Hi, it seems like there are some debate whether this conforming C99 or not. 
I'm not getting error or any warning with clang-12 and gcc-11 with -Wall -std=c99 -pedantic. I do get a warning with MSVC, 
So, it may be non-conforming, but because all "major" compilers allow it (with newest versions), I'll keep it for now. It's not a very important macro, and can be removed / replaced by using c_foreach .

**Comment by tylov** [comment]
I checked on reddit.com, this is conformant C code, and a bug in clang < version 12. Upgrade to v12 or newer.
