### ISSUE TITLE
about the name `cstr_trim`

### ISSUE THREAD

**Issue by liigo** [tylov/STC#7]
In many string libraries, 'trim' is normally defined to trim **space chars** (` ` `\t` `\n` etc.). But in STC, cstr_trim is currently implemented as similar like 'substring'. This may be confusing.

```c
STC_INLINE cstr* cstr_trim(cstr* self, size_t left, size_t right)
{ return cstr_assign_n(self, self->str + left, _cstr_rep(self)->size - left - right); }
```

**Comment by liigo** [comment]
But why the new `cstr_substr` `cstr_slice` change cstr itself? Just returns a `csview` or similar would be great.

**Comment by tylov** [comment]
Yes, I saw this myself also. Now there is both cstr and csview versions, but all return csview.  C++ has some strange string_view API:  remove_suffix() and remove_prefix(), which modifies views instead of just returning a new view..  csview/cstr substr + slice is much more user-friendly and flexible, and allows negative arguments.
